### ISSUE TITLE
.NET 7 Version

### ISSUE THREAD

**Issue by SebastianStehle** [f2calv/multi-arch-container-dotnet#2]
Hi,

I am also trying to get multiplatform working. I have adapted my dockerfile with the lessons hat you showcase here:

https://github.com/notifo-io/notifo/blob/multiplatform/Dockerfile

But I am running from error to error. Stuff like ArgumentNullException from .NET runtime and now this error:

```
 > [linux/arm/v7 backend  9/13] RUN dotnet restore --runtime $(cat /tmp/rid):
#53 11.41 Assertion failed: (dc->base.pc_next & 1) == 0 (../target/arm/translate.c: thumb_tr_translate_insn: 9650)
#53 11.77 Aborted (core dumped)
```

Have you tried it with .NET 7?

**Comment by f2calv** [comment]
I just updated the repo to .NET 7 and seems to be OK, I didn't look too closely at your Dockerfile yet, if you're still stuck I will take a look at the weekend just bump this issue :)

**Comment by SebastianStehle** [comment]
Thanks a lot for your answer.

Interesting, I have this problem now:

```
 > [linux/arm64 backend  9/13] RUN dotnet restore --runtime $(cat /tmp/rid):
#35 124.3 /usr/share/dotnet/sdk/7.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(54,5): error MSB4184: The expression "[MSBuild]::GetTargetFrameworkIdentifier(net7.0)" cannot be evaluated. Exception has been thrown by the target of an invocation. [/src/src/Notifo.Infrastructure/Notifo.Infrastructure.csproj]
```

It has been reported before: https://github.com/NuGet/Home/issues/12227... strange that it works for you.
